# Generated by Django 3.0.4 on 2020-08-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200728_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='user',
        ),
        migrations.DeleteModel(
            name='SellerAccount',
        ),
        migrations.AddField(
            model_name='myuser',
            name='name',
            field=models.CharField(blank=True, max_length=225, verbose_name='Name of User'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('Admin', 'ADMIN'), ('Editor', 'EDITOR'), ('Seller', 'SELLER'), ('Manager', 'MANAGER')], default=True),
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
